export const ActionType = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  SELECTED_PRODUCT: 'SELECTED_PRODUCT',
  REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
  CART_PRODUCT_LIST: 'CART_PRODUCT_LIST',
  ADD_TO_CART: 'ADD_TO_CART',
};
